"""Core use case specifications (đặc tả), activity and sequence definitions.

main: ordered steps ("A", text) = actor, ("S", text) = system; the builder numbers them.
alt:  (step/condition, handling)
activity: see diagrams.activity; seq: see diagrams.sequence.
"""

U = "Người dùng"

CORE = [
    # ------------------------------------------------------------------ 1
    dict(
        code="UC01", name="Đăng nhập", group="Chung (cả 3 phân hệ)",
        desc="Người dùng đã có tài khoản đăng nhập bằng email và mật khẩu để sử dụng cổng khách hàng, cổng quản trị hoặc ứng dụng vận hành. Hệ thống cấp access token và refresh token, sau đó điều hướng theo vai trò và quyền.",
        actor="Customer, Back-office User, Operational Staff", sub="Không",
        pre="Người dùng đã có tài khoản; tài khoản chưa bị khóa.",
        post="Người dùng được cấp phiên làm việc (access token, refresh token) và được chuyển đến trang chính tương ứng với vai trò.",
        main=[
            ("A", "Người dùng truy cập trang “Đăng nhập”."),
            ("S", "Hệ thống hiển thị form gồm email và mật khẩu."),
            ("A", "Người dùng nhập email, mật khẩu và nhấn “Đăng nhập”."),
            ("S", "Hệ thống kiểm tra dữ liệu bắt buộc và định dạng email."),
            ("S", "Hệ thống tìm tài khoản theo email, đối chiếu mật khẩu đã mã hóa và kiểm tra trạng thái tài khoản."),
            ("S", "Hệ thống tạo access token, refresh token và lưu phiên đăng nhập."),
            ("S", "Hệ thống lấy thông tin người dùng, vai trò, quyền và chuyển đến trang chính theo vai trò."),
        ],
        alt=[
            ("4a. Thiếu email/mật khẩu hoặc email sai định dạng", "Hệ thống báo lỗi tại trường nhập, quay lại bước 3."),
            ("5a. Email hoặc mật khẩu không đúng", "Hệ thống thông báo “Email hoặc mật khẩu không đúng”, quay lại bước 3."),
            ("5b. Tài khoản bị tạm khóa (SUSPENDED) hoặc vô hiệu hóa (DISABLED)", "Hệ thống thông báo tài khoản bị khóa và kết thúc use case."),
            ("7a. Access token hết hạn trong khi sử dụng", "Hệ thống dùng refresh token để cấp token mới; nếu refresh thất bại thì yêu cầu đăng nhập lại."),
            ("3a. Người dùng chọn “Quên mật khẩu”", "Chuyển sang use case Quên mật khẩu (extend)."),
        ],
        activity=[
            ("A", "Truy cập trang Đăng nhập"),
            ("S", "Hiển thị form đăng nhập"),
            ("A", "Nhập email, mật khẩu và nhấn Đăng nhập"),
            ("S", "Kiểm tra dữ liệu nhập"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi tại trường nhập"), 2),
            ("S", "Xác thực email, mật khẩu và trạng thái tài khoản"),
            ("?", "Đúng và đang hoạt động?", ("S", "Thông báo sai thông tin hoặc tài khoản bị khóa"), 2),
            ("S", "Cấp access token và refresh token"),
            ("S", "Chuyển đến trang chính theo vai trò"),
        ],
        seq=dict(
            parts=[("actor", U), ("boundary", "GD_DangNhap"), ("control", "CTRL_XacThuc"), ("entity", "UserAccount"), ("entity", "Role")],
            msgs=[
                (0, 1, "Nhập email, mật khẩu, nhấn Đăng nhập"),
                (1, 2, "login(email, password)"),
                (2, 3, "findByEmail(email)"),
                (3, 2, "account", "ret"),
                (2, 2, "Kiểm tra mật khẩu và trạng thái"),
                (2, 4, "getRolesAndPermissions(userId)"),
                (4, 2, "roles, permissions", "ret"),
                (2, 2, "Tạo access token, refresh token"),
                (2, 1, "tokens, currentUser", "ret"),
                (1, 0, "Chuyển đến trang chính theo vai trò"),
                (2, 1, "401 – sai thông tin hoặc tài khoản bị khóa", "ret"),
                (1, 0, "Hiển thị thông báo lỗi"),
            ],
            frags=[(4, 11, "alt", "[thông tin đúng, tài khoản ACTIVE]", 10, "[sai thông tin / bị khóa]")],
        ),
    ),
    # ------------------------------------------------------------------ 2
    dict(
        code="UC03", name="Đăng ký tài khoản", group="Cổng khách hàng",
        desc="Khách vãng lai tạo tài khoản khách hàng mới để tạo đơn, quản lý sổ địa chỉ và đăng ký cửa hàng.",
        actor="Guest", sub="Không",
        pre="Khách chưa đăng nhập; email chưa được đăng ký trong hệ thống.",
        post="Tài khoản khách hàng được tạo (hồ sơ ở trạng thái INCOMPLETE), email xác minh được gửi; sau khi xác minh, tài khoản có emailVerified = true.",
        main=[
            ("A", "Khách chọn “Đăng ký tài khoản”."),
            ("S", "Hệ thống hiển thị form gồm họ tên, email, mật khẩu và xác nhận mật khẩu."),
            ("A", "Khách nhập thông tin và nhấn “Đăng ký”."),
            ("S", "Hệ thống kiểm tra thông tin bắt buộc, định dạng email, độ mạnh mật khẩu và mật khẩu xác nhận."),
            ("S", "Hệ thống kiểm tra email chưa tồn tại."),
            ("S", "Hệ thống tạo UserAccount (vai trò khách hàng, hồ sơ INCOMPLETE) và UserProfile, mã hóa mật khẩu."),
            ("S", "Hệ thống gửi email xác minh và thông báo đăng ký thành công."),
            ("A", "Khách mở liên kết xác minh trong email."),
            ("S", "Hệ thống xác nhận email (emailVerified = true) và chuyển đến trang đăng nhập."),
        ],
        alt=[
            ("4a. Thiếu thông tin hoặc dữ liệu không hợp lệ", "Hệ thống báo lỗi tại từng trường, quay lại bước 3."),
            ("5a. Email đã được đăng ký", "Hệ thống thông báo email đã tồn tại và gợi ý Đăng nhập / Quên mật khẩu."),
            ("8a. Liên kết xác minh hết hạn", "Hệ thống cho phép gửi lại email xác minh."),
            ("3a. Khách nhấn “Hủy”", "Kết thúc use case, không lưu dữ liệu."),
        ],
        activity=[
            ("A", "Chọn Đăng ký tài khoản"),
            ("S", "Hiển thị form đăng ký"),
            ("A", "Nhập họ tên, email, mật khẩu và nhấn Đăng ký"),
            ("S", "Kiểm tra dữ liệu nhập"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi từng trường"), 2),
            ("S", "Kiểm tra email đã tồn tại"),
            ("?", "Email mới?", ("S", "Thông báo email đã được đăng ký"), "end"),
            ("S", "Tạo tài khoản và hồ sơ (INCOMPLETE)"),
            ("S", "Gửi email xác minh, báo đăng ký thành công"),
            ("A", "Mở liên kết xác minh"),
            ("S", "Xác nhận email, chuyển đến Đăng nhập"),
        ],
        seq=dict(
            parts=[("actor", "Guest"), ("boundary", "GD_DangKy"), ("control", "CTRL_TaiKhoan"), ("entity", "UserAccount"), ("system", "Dịch vụ Email")],
            msgs=[
                (0, 1, "Nhập thông tin, nhấn Đăng ký"),
                (1, 1, "Kiểm tra dữ liệu nhập"),
                (1, 2, "register(fullName, email, password)"),
                (2, 3, "existsByEmail(email)"),
                (3, 2, "false", "ret"),
                (2, 3, "create(account, profile INCOMPLETE)"),
                (3, 2, "userId", "ret"),
                (2, 4, "sendVerificationEmail(email, token)"),
                (2, 1, "Đăng ký thành công", "ret"),
                (1, 0, "Thông báo, yêu cầu xác minh email"),
                (2, 1, "409 – email đã tồn tại", "ret"),
                (1, 0, "Hiển thị lỗi email đã đăng ký"),
            ],
            frags=[(4, 11, "alt", "[email chưa tồn tại]", 10, "[email đã tồn tại]")],
        ),
    ),
    # ------------------------------------------------------------------ 3
    dict(
        code="UC15", name="Tra cứu giá cước", group="Cổng khách hàng",
        desc="Người dùng nhập điểm gửi, điểm nhận và thông tin kiện hàng để nhận các phương án giá theo mức dịch vụ (Tiết kiệm, Tiêu chuẩn, Nhanh). Báo giá được lưu và có thời hạn sử dụng khi tạo đơn.",
        actor="Public User (Guest, Customer, Merchant)", sub="Không",
        pre="Hệ thống có bảng giá đang áp dụng (RatePlan ACTIVE) và khu vực phục vụ cho điểm gửi/nhận.",
        post="QuoteRequest được lưu cùng các QuoteOption và thời điểm hết hạn; người dùng xem được cước phí và thời gian giao dự kiến.",
        main=[
            ("A", "Người dùng mở trang “Tính cước vận chuyển”."),
            ("S", "Hệ thống hiển thị form: tỉnh/phường gửi, tỉnh/phường nhận, loại hàng, khối lượng, kích thước, tiền thu hộ (COD), giá trị khai báo."),
            ("A", "Người dùng nhập thông tin và nhấn “Tính cước”."),
            ("S", "Hệ thống kiểm tra dữ liệu và giới hạn nhận gửi (khối lượng, kích thước tối đa)."),
            ("S", "Hệ thống xác định khu vực phục vụ, hub chính và hạng phủ sóng của điểm gửi và điểm nhận, từ đó suy ra vùng giá (nội tỉnh / nội vùng / liên vùng)."),
            ("S", "Hệ thống tính khối lượng quy đổi theo thể tích và khối lượng tính cước = max(thực tế, quy đổi)."),
            ("S", "Hệ thống áp dụng quy tắc giá cho từng mức dịch vụ; cộng phụ phí vùng xa/hải đảo, phí COD và phí bảo hiểm."),
            ("S", "Hệ thống lưu báo giá và hiển thị bảng phương án gồm phí chi tiết, tổng cước, thời gian giao dự kiến và hạn báo giá."),
        ],
        alt=[
            ("4a. Thiếu thông tin hoặc sai định dạng", "Hệ thống báo lỗi, quay lại bước 3."),
            ("4b. Vượt khối lượng/kích thước tối đa", "Hệ thống thông báo kiện hàng vượt giới hạn nhận gửi."),
            ("4c. Tiền COD hoặc giá trị khai báo vượt mức tối đa", "Hệ thống thông báo mức tối đa cho phép."),
            ("5a. Địa chỉ ngoài vùng phục vụ", "Hệ thống thông báo “Chưa hỗ trợ khu vực này”."),
            ("7a. Không có bảng giá đang áp dụng", "Hệ thống thông báo lỗi và đề nghị thử lại sau."),
        ],
        activity=[
            ("A", "Mở trang Tính cước"),
            ("S", "Hiển thị form tính cước"),
            ("A", "Nhập điểm gửi, điểm nhận, kiện hàng, COD và nhấn Tính cước"),
            ("S", "Kiểm tra dữ liệu và giới hạn nhận gửi"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi hoặc vượt giới hạn"), 2),
            ("S", "Xác định khu vực phục vụ và vùng giá"),
            ("?", "Trong vùng phục vụ?", ("S", "Thông báo chưa hỗ trợ khu vực"), "end"),
            ("S", "Tính khối lượng quy đổi và khối lượng tính cước"),
            ("S", "Áp dụng quy tắc giá, phụ phí, COD, bảo hiểm"),
            ("S", "Lưu báo giá, hiển thị các phương án dịch vụ"),
        ],
        seq=dict(
            parts=[("actor", "Public User"), ("boundary", "GD_TinhCuoc"), ("control", "CTRL_BaoGia"), ("entity", "ServiceAreaCoverage"), ("entity", "RatePlan"), ("entity", "QuoteRequest")],
            msgs=[
                (0, 1, "Nhập thông tin, nhấn Tính cước"),
                (1, 2, "createQuote(origin, destination, parcels, cod, declaredValue)"),
                (2, 2, "Kiểm tra giới hạn nhận gửi"),
                (2, 3, "resolve(province, ward) cho điểm gửi và nhận"),
                (3, 2, "serviceArea, primaryHub, coverageTier", "ret"),
                (2, 4, "findActivePlan(); findRule(serviceLevel, zone)"),
                (4, 2, "ratePlan, rateRules", "ret"),
                (2, 2, "Tính khối lượng tính cước, phí, phụ phí"),
                (2, 5, "save(quoteRequest, options, expiresAt)"),
                (5, 2, "quoteId", "ret"),
                (2, 1, "quoteId, options[]", "ret"),
                (1, 0, "Hiển thị bảng phương án và hạn báo giá"),
                (2, 1, "422 – ngoài vùng phục vụ", "ret"),
                (1, 0, "Thông báo chưa hỗ trợ khu vực"),
            ],
            frags=[(5, 13, "alt", "[trong vùng phục vụ]", 12, "[ngoài vùng phục vụ]")],
        ),
    ),
    # ------------------------------------------------------------------ 4
    dict(
        code="UC17", name="Tạo đơn hàng", group="Cổng khách hàng / Cổng quản trị",
        desc="Chủ cửa hàng (hoặc điều phối viên hub tạo tại quầy) tạo vận đơn từ báo giá còn hiệu lực. Hệ thống lưu ảnh chụp giá và địa chỉ, sinh mã vận đơn, định tuyến, giữ chỗ tải trên các tuyến và tạo công việc lấy hàng.",
        actor="Merchant", sub="Hub Dispatch (tạo đơn tại quầy)",
        pre="Người dùng đã đăng nhập; cửa hàng ở trạng thái ACTIVE (với Merchant); có địa chỉ lấy hàng.",
        post="Shipment và các Parcel được tạo với mã vận đơn; giá và địa chỉ được snapshot; lộ trình và giữ chỗ tải được ghi nhận; công việc lấy hàng (PICKUP) được tạo tại hub gốc; sự kiện “Tạo đơn” được ghi vào hành trình.",
        main=[
            ("A", "Người dùng chọn “Tạo đơn hàng”."),
            ("S", "Hệ thống hiển thị bước 1: người gửi (mặc định là địa chỉ lấy hàng) và người nhận."),
            ("A", "Người dùng chọn địa chỉ gửi và nhập (hoặc chọn từ sổ địa chỉ) thông tin người nhận."),
            ("S", "Hệ thống kiểm tra số điện thoại và địa chỉ hành chính."),
            ("A", "Người dùng khai báo kiện hàng: mô tả, loại hàng, dễ vỡ, khối lượng, kích thước."),
            ("S", "Hệ thống kiểm tra giới hạn từng kiện."),
            ("A", "Người dùng nhập tiền thu hộ (COD), giá trị khai báo, người trả cước và ghi chú."),
            ("S", "Hệ thống tính cước (include Tra cứu giá cước) và hiển thị các phương án dịch vụ."),
            ("A", "Người dùng chọn mức dịch vụ và nhấn “Xác nhận tạo đơn”."),
            ("S", "Hệ thống kiểm tra báo giá còn hiệu lực."),
            ("S", "Hệ thống tạo Shipment và Parcel, sinh mã vận đơn, lưu snapshot giá và địa chỉ."),
            ("S", "Hệ thống định tuyến và giữ chỗ tải trên các chuyến của từng chặng."),
            ("S", "Hệ thống tạo công việc lấy hàng tại hub gốc và ghi sự kiện “Tạo đơn”."),
            ("S", "Hệ thống hiển thị mã vận đơn và trạng thái “Chờ lấy hàng”."),
        ],
        alt=[
            ("4a. Số điện thoại hoặc địa chỉ không hợp lệ", "Hệ thống báo lỗi, quay lại bước 3."),
            ("6a. Kiện hàng vượt giới hạn", "Hệ thống báo lỗi, quay lại bước 5."),
            ("7a. COD hoặc giá trị khai báo vượt mức tối đa của bảng giá", "Hệ thống báo mức tối đa, quay lại bước 7."),
            ("10a. Báo giá đã hết hạn", "Hệ thống tính lại cước và quay lại bước 8."),
            ("12a. Không tìm được lộ trình hoặc hết tải trọng", "Đơn vẫn được tạo với trạng thái định tuyến ROUTING_FAILED và được đưa vào danh sách ngoại lệ để điều phối viên xử lý."),
            ("1a. Cửa hàng chưa được xác minh", "Hệ thống không cho tạo đơn và hướng dẫn gửi yêu cầu xác minh."),
        ],
        activity=[
            ("A", "Chọn Tạo đơn hàng"),
            ("S", "Hiển thị form người gửi / người nhận"),
            ("A", "Nhập người gửi, người nhận"),
            ("S", "Kiểm tra số điện thoại, địa chỉ"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi thông tin liên hệ"), 2),
            ("A", "Khai báo kiện hàng, COD, giá trị khai báo"),
            ("S", "Kiểm tra giới hạn, tính cước các phương án"),
            ("?", "Hợp lệ?", ("S", "Báo vượt giới hạn / mức COD"), 5),
            ("A", "Chọn dịch vụ, nhấn Xác nhận tạo đơn"),
            ("S", "Kiểm tra báo giá còn hiệu lực"),
            ("?", "Còn hạn?", ("S", "Tính lại cước"), 8),
            ("S", "Tạo vận đơn, kiện hàng, sinh mã vận đơn"),
            ("S", "Định tuyến và giữ chỗ tải"),
            ("S", "Tạo công việc lấy hàng, ghi sự kiện"),
            ("S", "Hiển thị mã vận đơn, trạng thái Chờ lấy hàng"),
        ],
        seq=dict(
            parts=[("actor", "Merchant"), ("boundary", "GD_TaoDonHang"), ("control", "CTRL_DonHang"), ("control", "CTRL_BaoGia"), ("entity", "Shipment"), ("entity", "LaneCapacityReservation"), ("entity", "OperationalAssignment")],
            msgs=[
                (0, 1, "Nhập người gửi, người nhận, kiện hàng, COD"),
                (1, 3, "createQuote(...)"),
                (3, 1, "options[], quoteId", "ret"),
                (0, 1, "Chọn dịch vụ, Xác nhận tạo đơn"),
                (1, 2, "createShipment(quoteId, serviceLevel, sender, recipient, parcels)"),
                (2, 3, "validateQuote(quoteId)"),
                (3, 2, "quote còn hiệu lực", "ret"),
                (2, 4, "create(shipment, parcels, trackingCode)"),
                (2, 2, "Tìm lộ trình (RouteTemplate / tuyến trực tiếp)"),
                (2, 5, "reserve(lane, schedule, weightKg)"),
                (5, 2, "reservation", "ret"),
                (2, 4, "markRouted(batchId)"),
                (2, 6, "create(PICKUP, originHub)"),
                (2, 4, "markRoutingFailed()"),
                (2, 1, "trackingCode, status", "ret"),
                (1, 0, "Hiển thị mã vận đơn và trạng thái"),
            ],
            frags=[(9, 13, "alt", "[tìm được lộ trình, còn tải]", 13, "[không có lộ trình / hết tải]"),
                   (9, 10, "loop", "[với mỗi chặng của lộ trình]")],
        ),
    ),
    # ------------------------------------------------------------------ 5
    dict(
        code="UC14 / UC19", name="Tra cứu và theo dõi vận đơn", group="Cổng khách hàng",
        desc="Người dùng tra cứu vận đơn bằng mã vận đơn để xem trạng thái hiện tại, tiến trình và hành trình (timeline). Chủ cửa hàng xem thêm chi tiết kiện hàng, cước phí và các lần giao.",
        actor="Public User, Merchant", sub="Không",
        pre="Người dùng có mã vận đơn hợp lệ (Merchant: vận đơn thuộc cửa hàng của mình).",
        post="Hệ thống hiển thị trạng thái, thanh tiến trình, thời gian giao dự kiến và các sự kiện hành trình theo thứ tự thời gian.",
        main=[
            ("A", "Người dùng truy cập “Tra cứu vận đơn” (hoặc chọn một đơn trong “Đơn hàng của tôi”)."),
            ("S", "Hệ thống hiển thị ô nhập mã vận đơn."),
            ("A", "Người dùng nhập mã vận đơn và nhấn “Tra cứu”."),
            ("S", "Hệ thống kiểm tra định dạng mã vận đơn."),
            ("S", "Hệ thống tìm vận đơn theo mã."),
            ("S", "Hệ thống lấy các sự kiện hành trình (include Xem hành trình vận đơn)."),
            ("S", "Hệ thống hiển thị trạng thái hiện tại, các bước tiến trình, thời gian giao dự kiến và timeline sự kiện."),
            ("A", "Merchant chọn “Chi tiết” để xem kiện hàng, cước phí, COD và các lần giao."),
            ("S", "Hệ thống hiển thị thông tin chi tiết của vận đơn."),
        ],
        alt=[
            ("4a. Mã vận đơn trống hoặc sai định dạng", "Hệ thống báo lỗi, quay lại bước 3."),
            ("5a. Không tìm thấy vận đơn", "Hệ thống thông báo “Vận đơn không tồn tại”."),
            ("7a. Người tra cứu không phải chủ vận đơn", "Hệ thống chỉ hiển thị thông tin rút gọn, ẩn số điện thoại và địa chỉ chi tiết."),
        ],
        activity=[
            ("A", "Truy cập Tra cứu vận đơn"),
            ("S", "Hiển thị ô nhập mã vận đơn"),
            ("A", "Nhập mã vận đơn, nhấn Tra cứu"),
            ("S", "Kiểm tra định dạng mã"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi mã vận đơn"), 2),
            ("S", "Tìm vận đơn theo mã"),
            ("?", "Tồn tại?", ("S", "Thông báo vận đơn không tồn tại"), "end"),
            ("S", "Lấy sự kiện hành trình"),
            ("S", "Hiển thị trạng thái, tiến trình, timeline"),
        ],
        seq=dict(
            parts=[("actor", "Người tra cứu"), ("boundary", "GD_TraCuuVanDon"), ("control", "CTRL_VanDon"), ("entity", "Shipment"), ("entity", "ShipmentEvent")],
            msgs=[
                (0, 1, "Nhập mã vận đơn, nhấn Tra cứu"),
                (1, 2, "track(trackingCode)"),
                (2, 3, "findByTrackingCode(code)"),
                (3, 2, "shipment", "ret"),
                (2, 4, "findByShipment(id) order by occurredAt"),
                (4, 2, "events[]", "ret"),
                (2, 2, "Ẩn thông tin cá nhân nếu không phải chủ đơn"),
                (2, 1, "trackingView", "ret"),
                (1, 0, "Hiển thị trạng thái và timeline"),
                (2, 1, "404 – không tìm thấy", "ret"),
                (1, 0, "Thông báo vận đơn không tồn tại"),
            ],
            frags=[(4, 10, "alt", "[tìm thấy vận đơn]", 9, "[không tìm thấy]")],
        ),
    ),
    # ------------------------------------------------------------------ 6
    dict(
        code="UC13", name="Duyệt và quản lý cửa hàng", group="Cổng quản trị",
        desc="Quản trị nền tảng xem các cửa hàng chờ xác minh, duyệt hoặc từ chối kèm lý do, và tạm ngưng / khôi phục cửa hàng đang hoạt động.",
        actor="Platform Admin", sub="Merchant (nhận thông báo)",
        pre="Admin đã đăng nhập và có quyền quản lý cửa hàng; có cửa hàng ở trạng thái PENDING_VERIFICATION.",
        post="Cửa hàng chuyển sang ACTIVE (ghi verifiedAt, verifiedBy) hoặc REJECTED/SUSPENDED kèm mã lý do; người thay đổi và thời điểm được ghi nhận; chủ cửa hàng được thông báo.",
        main=[
            ("A", "Admin mở “Quản lý cửa hàng”."),
            ("S", "Hệ thống hiển thị danh sách cửa hàng, cho phép lọc theo trạng thái và tìm theo mã/tên."),
            ("A", "Admin chọn một cửa hàng đang chờ xác minh."),
            ("S", "Hệ thống hiển thị chi tiết: tên kinh doanh, mã số thuế, người liên hệ, địa chỉ lấy hàng."),
            ("A", "Admin kiểm tra thông tin và chọn “Duyệt”."),
            ("S", "Hệ thống kiểm tra trạng thái hiện tại cho phép chuyển sang ACTIVE."),
            ("S", "Hệ thống cập nhật trạng thái ACTIVE, ghi verifiedAt, verifiedBy, statusChangedAt."),
            ("S", "Hệ thống thông báo cho chủ cửa hàng và hiển thị “Duyệt cửa hàng thành công”."),
        ],
        alt=[
            ("5a. Admin chọn “Từ chối”", "Admin chọn mã lý do (thiếu giấy tờ, thông tin không hợp lệ…) và nhập chi tiết; hệ thống chuyển REJECTED và thông báo cho chủ cửa hàng."),
            ("5b. Admin tạm ngưng cửa hàng đang hoạt động", "Hệ thống yêu cầu lý do và chuyển SUSPENDED; cửa hàng không thể tạo đơn mới."),
            ("5c. Admin khôi phục cửa hàng bị tạm ngưng", "Hệ thống chuyển lại ACTIVE."),
            ("6a. Trạng thái đã bị người khác thay đổi", "Hệ thống báo xung đột dữ liệu và tải lại chi tiết."),
        ],
        activity=[
            ("A", "Mở Quản lý cửa hàng"),
            ("S", "Hiển thị danh sách, lọc theo trạng thái"),
            ("A", "Chọn cửa hàng chờ xác minh"),
            ("S", "Hiển thị chi tiết cửa hàng"),
            ("A", "Chọn Duyệt hoặc Từ chối"),
            ("?", "Duyệt?", ("S", "Yêu cầu lý do, chuyển REJECTED, thông báo"), "end"),
            ("S", "Kiểm tra trạng thái cho phép chuyển"),
            ("?", "Hợp lệ?", ("S", "Báo xung đột, tải lại chi tiết"), 3),
            ("S", "Chuyển ACTIVE, ghi người duyệt"),
            ("S", "Thông báo cho chủ cửa hàng"),
        ],
        seq=dict(
            parts=[("actor", "Platform Admin"), ("boundary", "GD_QuanLyCuaHang"), ("control", "CTRL_CuaHang"), ("entity", "Merchant"), ("system", "Dịch vụ thông báo")],
            msgs=[
                (0, 1, "Mở Quản lý cửa hàng, lọc Chờ xác minh"),
                (1, 2, "list(status=PENDING_VERIFICATION)"),
                (2, 3, "findByStatus(...)"),
                (3, 2, "merchants[]", "ret"),
                (0, 1, "Chọn cửa hàng, nhấn Duyệt"),
                (1, 2, "verify(merchantId)"),
                (2, 3, "findById(merchantId)"),
                (3, 2, "merchant", "ret"),
                (2, 2, "Kiểm tra chuyển trạng thái hợp lệ"),
                (2, 3, "update(status=ACTIVE, verifiedAt, verifiedBy)"),
                (2, 4, "notify(owner, MERCHANT_VERIFIED)"),
                (2, 1, "ok", "ret"),
                (1, 0, "Thông báo duyệt thành công"),
            ],
        ),
    ),
    # ------------------------------------------------------------------ 7
    dict(
        code="UC31", name="Điều phối công việc", group="Cổng quản trị",
        desc="Điều phối viên hub phân công các công việc vận hành (lấy hàng, nhập hub, phân loại, trung chuyển, giao hàng, hoàn hàng) cho nhân sự phù hợp; có thể phân công lại hoặc hủy công việc.",
        actor="Hub Dispatch (Hub Manager kế thừa)", sub="Operational Staff (nhận công việc)",
        pre="Điều phối viên đã đăng nhập và thuộc hub; có công việc ở trạng thái PENDING tại hub.",
        post="Công việc chuyển ASSIGNED với người thực hiện, người phân công và thời điểm phân công; nhân sự nhận được công việc trên ứng dụng vận hành.",
        main=[
            ("A", "Điều phối viên mở “Điều phối công việc”."),
            ("S", "Hệ thống hiển thị các công việc chờ tại hub, sắp theo mức ưu tiên và loại công việc."),
            ("A", "Điều phối viên chọn một hoặc nhiều công việc."),
            ("S", "Hệ thống hiển thị nhân sự phù hợp (include Xem nhân sự vận hành): đúng loại nhân sự yêu cầu, thuộc hub, đã check-in ca, đang sẵn sàng và chưa vượt số việc đồng thời."),
            ("A", "Điều phối viên chọn nhân sự và nhấn “Phân công”."),
            ("S", "Hệ thống kiểm tra lại điều kiện của nhân sự."),
            ("S", "Hệ thống cập nhật công việc ASSIGNED, gán người thực hiện, ghi người phân công và thời điểm."),
            ("S", "Hệ thống đẩy công việc đến ứng dụng của nhân sự và hiển thị “Phân công thành công”."),
        ],
        alt=[
            ("4a. Không có nhân sự phù hợp", "Hệ thống thông báo không có nhân sự sẵn sàng; công việc giữ nguyên PENDING."),
            ("6a. Nhân sự vừa quá tải hoặc đã kết thúc ca", "Hệ thống cảnh báo và yêu cầu chọn nhân sự khác."),
            ("3a. Phân công lại", "Điều phối viên chọn công việc ASSIGNED/ACCEPTED và đổi người thực hiện; hệ thống ghi lại người thao tác."),
            ("3b. Hủy công việc", "Điều phối viên nhập ghi chú; hệ thống chuyển CANCELLED."),
        ],
        activity=[
            ("A", "Mở Điều phối công việc"),
            ("S", "Hiển thị công việc chờ tại hub"),
            ("A", "Chọn công việc"),
            ("S", "Lọc nhân sự phù hợp (loại, ca, sẵn sàng, tải việc)"),
            ("?", "Có nhân sự?", ("S", "Thông báo không có nhân sự sẵn sàng"), "end"),
            ("A", "Chọn nhân sự, nhấn Phân công"),
            ("S", "Kiểm tra lại điều kiện nhân sự"),
            ("?", "Còn hợp lệ?", ("S", "Cảnh báo, yêu cầu chọn nhân sự khác"), 5),
            ("S", "Cập nhật ASSIGNED, gán người thực hiện"),
            ("S", "Gửi công việc đến ứng dụng nhân sự"),
        ],
        seq=dict(
            parts=[("actor", "Hub Dispatch"), ("boundary", "GD_DieuPhoi"), ("control", "CTRL_PhanCong"), ("entity", "OperationalAssignment"), ("entity", "WorkforceMember"), ("system", "Ứng dụng vận hành")],
            msgs=[
                (0, 1, "Mở Điều phối công việc"),
                (1, 2, "listPending(hubId)"),
                (2, 3, "findByHubAndStatus(hubId, PENDING)"),
                (3, 2, "assignments[]", "ret"),
                (0, 1, "Chọn công việc"),
                (1, 2, "eligibleMembers(assignmentId)"),
                (2, 4, "find(kind, hub, checkedIn, AVAILABLE, load < max)"),
                (4, 2, "members[]", "ret"),
                (0, 1, "Chọn nhân sự, nhấn Phân công"),
                (1, 2, "assign(assignmentId, memberId)"),
                (2, 2, "Kiểm tra lại điều kiện"),
                (2, 3, "update(ASSIGNED, assignee, assignedBy, assignedAt)"),
                (2, 5, "push(newAssignment)"),
                (2, 1, "ok", "ret"),
                (1, 0, "Thông báo phân công thành công"),
            ],
        ),
    ),
    # ------------------------------------------------------------------ 8
    dict(
        code="UC33 / UC34", name="Thực hiện công việc và quét kiện hàng", group="Ứng dụng vận hành",
        desc="Nhân sự vận hành nhận công việc được giao, bắt đầu thực hiện, quét mã từng kiện để chuyển giao trách nhiệm (custody) và cập nhật vị trí, sau đó hoàn thành công việc.",
        actor="Operational Staff (Courier, Line-haul Driver, Warehouse Operator)", sub="Không",
        pre="Nhân sự đã đăng nhập ứng dụng vận hành, đã check-in ca và có công việc ở trạng thái ASSIGNED.",
        post="Công việc ở trạng thái COMPLETED (hoặc FAILED); các kiện được cập nhật custody, vị trí, công đoạn; sự kiện hành trình được ghi; công việc chặng tiếp theo được tạo.",
        main=[
            ("A", "Nhân sự mở “Công việc của tôi”."),
            ("S", "Hệ thống hiển thị các công việc được giao theo mức ưu tiên."),
            ("A", "Nhân sự chọn công việc và nhấn “Nhận việc”."),
            ("S", "Hệ thống chuyển công việc sang ACCEPTED."),
            ("A", "Nhân sự nhấn “Bắt đầu”."),
            ("S", "Hệ thống chuyển công việc sang IN_PROGRESS và bật màn hình quét mã."),
            ("A", "Nhân sự quét mã từng kiện hàng."),
            ("S", "Hệ thống giải mã, kiểm tra kiện thuộc vận đơn của công việc và đúng hub/công đoạn."),
            ("S", "Hệ thống cập nhật custody, vị trí, công đoạn của kiện và ghi sự kiện hành trình."),
            ("A", "Sau khi quét đủ, nhân sự nhấn “Hoàn thành”."),
            ("S", "Hệ thống kiểm tra đã quét đủ kiện."),
            ("S", "Hệ thống chuyển công việc sang COMPLETED, cập nhật trạng thái vận đơn và tạo công việc cho chặng tiếp theo."),
        ],
        alt=[
            ("7a. Chưa cấp quyền camera", "Ứng dụng yêu cầu cấp quyền hoặc cho phép nhập mã thủ công."),
            ("8a. Mã không hợp lệ hoặc kiện không thuộc công việc", "Hệ thống cảnh báo và không ghi nhận lần quét."),
            ("8b. Kiện đã được quét trước đó", "Hệ thống báo quét trùng và bỏ qua."),
            ("8c. Kiện không xác định được vận đơn", "Nhân sự chọn “Báo cáo sự cố” (loại UNIDENTIFIED_PARCEL)."),
            ("11a. Chưa quét đủ kiện", "Hệ thống không cho hoàn thành và hiển thị danh sách kiện còn thiếu."),
            ("10a. Không thể hoàn thành công việc", "Nhân sự chọn “Báo không hoàn thành” và nhập lý do; hệ thống chuyển FAILED."),
        ],
        activity=[
            ("A", "Mở Công việc của tôi"),
            ("S", "Hiển thị công việc được giao"),
            ("A", "Nhận việc và nhấn Bắt đầu"),
            ("S", "Chuyển IN_PROGRESS, bật quét mã"),
            ("A", "Quét mã kiện hàng"),
            ("S", "Kiểm tra kiện thuộc công việc, đúng hub"),
            ("?", "Hợp lệ?", ("S", "Cảnh báo mã sai hoặc quét trùng"), 4),
            ("S", "Cập nhật custody, vị trí, ghi sự kiện"),
            ("A", "Nhấn Hoàn thành"),
            ("S", "Kiểm tra đã quét đủ kiện"),
            ("?", "Đủ kiện?", ("S", "Hiển thị kiện còn thiếu"), 4),
            ("S", "Chuyển COMPLETED, tạo công việc chặng tiếp"),
        ],
        seq=dict(
            parts=[("actor", "Operational Staff"), ("boundary", "GD_QuetMa"), ("control", "CTRL_CongViec"), ("entity", "OperationalAssignment"), ("entity", "Parcel"), ("entity", "ShipmentEvent")],
            msgs=[
                (0, 1, "Nhận việc, nhấn Bắt đầu"),
                (1, 2, "start(assignmentId)"),
                (2, 3, "update(IN_PROGRESS, startedAt)"),
                (0, 1, "Quét mã kiện"),
                (1, 2, "scan(assignmentId, parcelCode)"),
                (2, 4, "findByCode(parcelCode)"),
                (4, 2, "parcel", "ret"),
                (2, 2, "Kiểm tra kiện thuộc công việc, đúng hub"),
                (2, 4, "updateCustody(member, hub, stage)"),
                (2, 5, "append(SCANNED, hub, actor)"),
                (2, 1, "Đã ghi nhận kiện", "ret"),
                (0, 1, "Nhấn Hoàn thành"),
                (1, 2, "complete(assignmentId)"),
                (2, 3, "update(COMPLETED, completedAt); tạo công việc chặng tiếp"),
                (2, 1, "ok", "ret"),
            ],
            frags=[(3, 10, "loop", "[với mỗi kiện của công việc]")],
        ),
    ),
    # ------------------------------------------------------------------ 9
    dict(
        code="UC35", name="Ghi nhận kết quả giao hàng", group="Ứng dụng vận hành",
        desc="Bưu tá ghi nhận kết quả giao từng kiện cho người nhận: giao thành công kèm bằng chứng (chữ ký, ảnh hoặc OTP) và thu COD, hoặc giao thất bại kèm lý do.",
        actor="Courier", sub="Không",
        pre="Bưu tá đã đăng nhập; công việc giao hàng (LAST_MILE_DELIVERY) đang IN_PROGRESS; kiện đang do bưu tá giữ.",
        post="DeliveryAttempt được ghi nhận; vận đơn chuyển DELIVERED (ghi completedAt) hoặc DELIVERY_FAILED; sự kiện hành trình được ghi; công việc giao hoàn tất.",
        main=[
            ("A", "Bưu tá đến địa chỉ người nhận và mở vận đơn trong công việc."),
            ("S", "Hệ thống hiển thị thông tin người nhận, số tiền COD cần thu và danh sách kiện."),
            ("A", "Bưu tá giao hàng và chọn “Giao thành công”."),
            ("S", "Hệ thống yêu cầu bằng chứng giao (chữ ký, ảnh hoặc OTP) và tên người nhận."),
            ("A", "Bưu tá cung cấp bằng chứng và xác nhận đã thu COD."),
            ("S", "Hệ thống kiểm tra bằng chứng."),
            ("S", "Hệ thống ghi DeliveryAttempt (DELIVERED, tọa độ GPS) và cập nhật kiện, vận đơn sang DELIVERED."),
            ("S", "Hệ thống ghi sự kiện “Giao thành công”, hoàn tất công việc và hiển thị kết quả."),
        ],
        alt=[
            ("3a. Không giao được", "Bưu tá chọn “Giao thất bại” và lý do (không liên lạc được, sai địa chỉ, người nhận từ chối, hẹn giao lại…); hệ thống ghi DeliveryAttempt FAILED, vận đơn DELIVERY_FAILED và đưa vào danh sách ngoại lệ."),
            ("6a. Thiếu bằng chứng giao", "Hệ thống yêu cầu bổ sung trước khi xác nhận."),
            ("5a. Số tiền COD thu không khớp", "Hệ thống cảnh báo và yêu cầu kiểm tra lại."),
        ],
        activity=[
            ("A", "Mở vận đơn tại địa chỉ người nhận"),
            ("S", "Hiển thị người nhận, COD, danh sách kiện"),
            ("A", "Chọn kết quả giao"),
            ("?", "Giao thành công?", ("S", "Ghi lần giao thất bại kèm lý do, đưa vào ngoại lệ"), "end"),
            ("S", "Yêu cầu bằng chứng giao, tên người nhận"),
            ("A", "Cung cấp bằng chứng, xác nhận thu COD"),
            ("S", "Kiểm tra bằng chứng"),
            ("?", "Đầy đủ?", ("S", "Yêu cầu bổ sung bằng chứng"), 5),
            ("S", "Ghi DeliveryAttempt, vận đơn DELIVERED"),
            ("S", "Ghi sự kiện, hoàn tất công việc"),
        ],
        seq=dict(
            parts=[("actor", "Courier"), ("boundary", "GD_GiaoHang"), ("control", "CTRL_GiaoHang"), ("entity", "DeliveryAttempt"), ("entity", "Shipment"), ("entity", "ShipmentEvent")],
            msgs=[
                (0, 1, "Chọn Giao thành công, gửi bằng chứng"),
                (1, 2, "recordDelivery(parcelId, proof, recipientName, gps)"),
                (2, 2, "Kiểm tra bằng chứng, COD"),
                (2, 3, "save(DELIVERED, attemptNumber, proof)"),
                (2, 4, "markDelivered(completedAt)"),
                (2, 5, "append(DELIVERED)"),
                (2, 1, "ok", "ret"),
                (1, 0, "Hiển thị giao thành công"),
                (0, 1, "Chọn Giao thất bại, chọn lý do"),
                (1, 2, "recordFailure(parcelId, reason, note)"),
                (2, 3, "save(FAILED, failureReason)"),
                (2, 4, "update(status=DELIVERY_FAILED)"),
                (2, 1, "ok", "ret"),
            ],
            frags=[(0, 12, "alt", "[giao thành công]", 8, "[giao thất bại]")],
        ),
    ),
    # ------------------------------------------------------------------ 10
    dict(
        code="UC40", name="Xử lý yêu cầu ngoại lệ", group="Cổng quản trị",
        desc="Điều phối viên hub xem và xử lý các yêu cầu ngoại lệ của vận đơn (hoàn hàng, chuyển tiếp địa chỉ mới, giao lại, hủy vận đơn): phê duyệt hoặc từ chối, định tuyến lại khi cần và hoàn tất yêu cầu.",
        actor="Hub Dispatch", sub="Merchant (người gửi yêu cầu)",
        pre="Điều phối viên đã đăng nhập; có yêu cầu ngoại lệ PENDING thuộc hub.",
        post="Yêu cầu ở trạng thái COMPLETED hoặc REJECTED với ghi chú duyệt; nếu cần định tuyến lại, vận đơn có lộ trình và giữ chỗ tải mới; người yêu cầu được thông báo.",
        main=[
            ("A", "Điều phối viên mở “Yêu cầu ngoại lệ”."),
            ("S", "Hệ thống hiển thị các yêu cầu đang chờ của hub."),
            ("A", "Điều phối viên chọn một yêu cầu."),
            ("S", "Hệ thống hiển thị loại yêu cầu, lý do, vận đơn liên quan và địa chỉ mới (nếu có)."),
            ("A", "Điều phối viên chọn “Phê duyệt” và nhập ghi chú."),
            ("S", "Hệ thống kiểm tra vận đơn còn cho phép thay đổi và chuyển yêu cầu sang APPROVED."),
            ("S", "Nếu cần định tuyến lại: hệ thống giải phóng giữ chỗ cũ, tìm lộ trình và giữ chỗ tải mới."),
            ("S", "Hệ thống cập nhật vận đơn theo loại yêu cầu (chiều hoàn, người nhận mới, giao lại hoặc hủy) và tạo công việc tương ứng."),
            ("S", "Hệ thống chuyển yêu cầu sang COMPLETED và thông báo cho người yêu cầu."),
        ],
        alt=[
            ("5a. Điều phối viên chọn “Từ chối”", "Hệ thống yêu cầu ghi chú, chuyển REJECTED và thông báo cho người yêu cầu."),
            ("6a. Vận đơn đã giao hoặc đã hủy", "Hệ thống không cho phê duyệt và thông báo lý do."),
            ("7a. Không tìm được lộ trình mới", "Yêu cầu giữ APPROVED, vận đơn ở trạng thái định tuyến lại thất bại và được cảnh báo cho điều phối viên."),
        ],
        activity=[
            ("A", "Mở danh sách yêu cầu ngoại lệ"),
            ("S", "Hiển thị yêu cầu đang chờ"),
            ("A", "Chọn yêu cầu, xem chi tiết"),
            ("A", "Chọn Phê duyệt hoặc Từ chối"),
            ("?", "Phê duyệt?", ("S", "Ghi chú, chuyển REJECTED, thông báo"), "end"),
            ("S", "Kiểm tra vận đơn còn cho phép thay đổi"),
            ("?", "Cho phép?", ("S", "Thông báo không thể phê duyệt"), "end"),
            ("S", "Chuyển APPROVED, định tuyến lại nếu cần"),
            ("S", "Cập nhật vận đơn, tạo công việc"),
            ("S", "Chuyển COMPLETED, thông báo người yêu cầu"),
        ],
        seq=dict(
            parts=[("actor", "Hub Dispatch"), ("boundary", "GD_YeuCauNgoaiLe"), ("control", "CTRL_NgoaiLe"), ("entity", "ShipmentExceptionRequest"), ("control", "CTRL_DinhTuyen"), ("entity", "Shipment")],
            msgs=[
                (0, 1, "Chọn yêu cầu, nhấn Phê duyệt"),
                (1, 2, "approve(requestId, note)"),
                (2, 3, "findById(requestId)"),
                (3, 2, "request", "ret"),
                (2, 5, "checkModifiable(shipmentId)"),
                (5, 2, "modifiable", "ret"),
                (2, 3, "update(APPROVED, reviewedBy, reviewedAt)"),
                (2, 4, "reroute(shipmentId, newEndpoint)"),
                (4, 2, "routeRevision mới", "ret"),
                (2, 5, "apply(kind: RETURN / FORWARD / REDELIVERY / CANCEL)"),
                (2, 3, "update(COMPLETED, completedBy, completedAt)"),
                (2, 1, "ok", "ret"),
                (1, 0, "Thông báo xử lý thành công"),
            ],
            frags=[(7, 8, "opt", "[routingRequired = true]")],
        ),
    ),
    # ------------------------------------------------------------------ 11
    dict(
        code="UC25", name="Quản lý ca làm việc", group="Cổng quản trị",
        desc="Trưởng hub hoặc quản lý vận hành tạo ca làm việc tại hub, phân công nhân sự vào ca, hủy ca hoặc đánh dấu vắng mặt.",
        actor="Hub Manager, Operations Manager", sub="Operational Staff (nhận lịch ca)",
        pre="Người quản lý đã đăng nhập; hub có nhân sự đang hoạt động.",
        post="Ca làm việc được tạo ở trạng thái SCHEDULED cùng danh sách phân công ASSIGNED; nhân sự nhận được lịch ca.",
        main=[
            ("A", "Người quản lý mở “Ca làm việc”."),
            ("S", "Hệ thống hiển thị lịch ca theo hub và theo ngày."),
            ("A", "Người quản lý chọn “Tạo ca”, nhập mã ca, tên ca, giờ bắt đầu, giờ kết thúc."),
            ("S", "Hệ thống kiểm tra thời gian (kết thúc sau bắt đầu) và mã ca không trùng."),
            ("S", "Hệ thống lưu ca ở trạng thái SCHEDULED."),
            ("A", "Người quản lý chọn “Phân công nhân sự” và chọn các nhân sự."),
            ("S", "Hệ thống kiểm tra nhân sự đang hoạt động, thuộc hub và không trùng ca khác."),
            ("S", "Hệ thống tạo các phân công ca (ASSIGNED), gửi thông báo lịch ca cho nhân sự và hiển thị kết quả."),
        ],
        alt=[
            ("4a. Thời gian không hợp lệ hoặc trùng mã ca", "Hệ thống báo lỗi, quay lại bước 3."),
            ("7a. Nhân sự đã có ca trùng thời gian", "Hệ thống cảnh báo và bỏ qua nhân sự đó."),
            ("5a. Hủy ca", "Người quản lý nhập lý do; hệ thống chuyển ca CANCELLED và hủy các phân công."),
            ("5b. Đánh dấu vắng mặt", "Người quản lý chọn nhân sự không đến ca; hệ thống chuyển phân công sang ABSENT."),
        ],
        activity=[
            ("A", "Mở Ca làm việc"),
            ("S", "Hiển thị lịch ca theo hub"),
            ("A", "Tạo ca: mã, tên, giờ bắt đầu, kết thúc"),
            ("S", "Kiểm tra thời gian, mã ca"),
            ("?", "Hợp lệ?", ("S", "Báo lỗi thời gian / trùng mã"), 2),
            ("S", "Lưu ca SCHEDULED"),
            ("A", "Chọn nhân sự để phân công"),
            ("S", "Kiểm tra nhân sự thuộc hub, không trùng ca"),
            ("?", "Hợp lệ?", ("S", "Cảnh báo trùng ca, bỏ qua nhân sự"), 6),
            ("S", "Tạo phân công ca, thông báo nhân sự"),
        ],
        seq=dict(
            parts=[("actor", "Hub Manager"), ("boundary", "GD_CaLamViec"), ("control", "CTRL_CaLamViec"), ("entity", "WorkShift"), ("entity", "WorkforceShiftAssignment"), ("system", "Ứng dụng vận hành")],
            msgs=[
                (0, 1, "Nhập thông tin ca, nhấn Tạo"),
                (1, 2, "createShift(hubId, code, name, startsAt, endsAt)"),
                (2, 2, "Kiểm tra thời gian, mã ca"),
                (2, 3, "save(SCHEDULED, createdBy)"),
                (3, 2, "shiftId", "ret"),
                (0, 1, "Chọn nhân sự, nhấn Phân công"),
                (1, 2, "assignMembers(shiftId, memberIds)"),
                (2, 4, "existsOverlap(memberId, startsAt, endsAt)"),
                (4, 2, "false", "ret"),
                (2, 4, "save(ASSIGNED, assignedBy)"),
                (2, 5, "notify(member, shift)"),
                (2, 1, "ok", "ret"),
                (1, 0, "Hiển thị lịch ca đã phân công"),
            ],
            frags=[(7, 10, "loop", "[với mỗi nhân sự được chọn]")],
        ),
    ),
    # ------------------------------------------------------------------ 12
    dict(
        code="UC06 / UC08", name="Quản lý người dùng và phân quyền", group="Cổng quản trị",
        desc="Quản trị nền tảng tra cứu, lọc và xem chi tiết tài khoản; thay đổi trạng thái tài khoản (hoạt động, tạm khóa, vô hiệu hóa), gán vai trò và phân quyền cho vai trò.",
        actor="Platform Admin", sub="Không",
        pre="Admin đã đăng nhập và có quyền identity.users.read / identity.roles.read cùng quyền cập nhật tương ứng.",
        post="Thông tin tài khoản, trạng thái hoặc vai trò được cập nhật; phiên bản dữ liệu tăng; nếu tài khoản bị khóa thì các phiên đăng nhập bị vô hiệu.",
        main=[
            ("A", "Admin mở “Người dùng”."),
            ("S", "Hệ thống hiển thị danh sách tài khoản có phân trang: email, tên, vai trò, trạng thái tài khoản, trạng thái hồ sơ, ngày tạo."),
            ("A", "Admin tìm theo email/tên và lọc theo vai trò, trạng thái tài khoản, trạng thái hồ sơ."),
            ("S", "Hệ thống trả về danh sách đã lọc."),
            ("A", "Admin chọn một tài khoản."),
            ("S", "Hệ thống hiển thị chi tiết tài khoản, hồ sơ và vai trò."),
            ("A", "Admin thay đổi trạng thái hoặc vai trò và nhấn “Lưu”."),
            ("S", "Hệ thống kiểm tra quyền thao tác và phiên bản dữ liệu (version)."),
            ("S", "Hệ thống cập nhật tài khoản; nếu tài khoản bị khóa thì thu hồi các phiên đăng nhập."),
            ("S", "Hệ thống thông báo “Cập nhật thành công”."),
        ],
        alt=[
            ("8a. Dữ liệu đã bị thay đổi bởi người khác (xung đột version)", "Hệ thống báo xung đột và tải lại dữ liệu mới nhất."),
            ("8b. Admin tự khóa tài khoản của chính mình", "Hệ thống không cho phép."),
            ("8c. Sửa hoặc xóa vai trò hệ thống", "Hệ thống không cho phép thay đổi vai trò hệ thống."),
            ("1a. Không đủ quyền", "Hệ thống trả lỗi 403 và hiển thị thông báo chưa được cấp quyền."),
        ],
        activity=[
            ("A", "Mở Người dùng"),
            ("S", "Hiển thị danh sách có phân trang"),
            ("A", "Tìm kiếm, lọc theo vai trò / trạng thái"),
            ("S", "Trả về danh sách đã lọc"),
            ("A", "Chọn tài khoản, đổi trạng thái hoặc vai trò, nhấn Lưu"),
            ("S", "Kiểm tra quyền và phiên bản dữ liệu"),
            ("?", "Hợp lệ?", ("S", "Báo xung đột / không đủ quyền, tải lại"), 4),
            ("S", "Cập nhật tài khoản, thu hồi phiên nếu bị khóa"),
            ("S", "Thông báo cập nhật thành công"),
        ],
        seq=dict(
            parts=[("actor", "Platform Admin"), ("boundary", "GD_NguoiDung"), ("control", "CTRL_NguoiDung"), ("entity", "UserAccount"), ("entity", "Role"), ("entity", "RefreshToken")],
            msgs=[
                (0, 1, "Tìm kiếm, lọc người dùng"),
                (1, 2, "listUsers(page, search, role, status, profileStatus)"),
                (2, 3, "search(criteria)"),
                (3, 2, "page<UserListItem>", "ret"),
                (0, 1, "Đổi trạng thái / vai trò, nhấn Lưu"),
                (1, 2, "updateUser(userId, status, roles, version)"),
                (2, 3, "findById(userId)"),
                (3, 2, "account(version)", "ret"),
                (2, 2, "Kiểm tra quyền, so sánh version"),
                (2, 4, "findByCodes(roles)"),
                (2, 3, "save(status, roles, version + 1)"),
                (2, 5, "revokeAll(userId) nếu tài khoản bị khóa"),
                (2, 1, "ok", "ret"),
                (1, 0, "Thông báo cập nhật thành công"),
            ],
            frags=[(11, 11, "opt", "[status = SUSPENDED hoặc DISABLED]")],
        ),
    ),
]


# guards of the decision nodes in the activity diagrams: question -> ([yes], [no])
GUARDS = {
    "Hợp lệ?": ("hợp lệ", "không hợp lệ"),
    "Đúng và đang hoạt động?": ("đúng, ACTIVE", "sai / bị khóa"),
    "Email mới?": ("email chưa tồn tại", "email đã tồn tại"),
    "Trong vùng phục vụ?": ("trong vùng phục vụ", "ngoài vùng"),
    "Còn hạn?": ("báo giá còn hạn", "báo giá hết hạn"),
    "Tồn tại?": ("tìm thấy", "không tìm thấy"),
    "Duyệt?": ("duyệt", "từ chối"),
    "Có nhân sự?": ("có nhân sự sẵn sàng", "không có nhân sự"),
    "Còn hợp lệ?": ("còn hợp lệ", "không còn hợp lệ"),
    "Đủ kiện?": ("đủ kiện", "còn thiếu kiện"),
    "Giao thành công?": ("giao thành công", "giao thất bại"),
    "Đầy đủ?": ("đủ bằng chứng", "thiếu bằng chứng"),
    "Phê duyệt?": ("phê duyệt", "từ chối"),
    "Cho phép?": ("được phép", "không được phép"),
}
