"""Test cases: one per function that is implemented in code (management portal + identity API).

Fields follow ISO/IEC/IEEE 29119-3 test case specification: identifier, objective, preconditions,
inputs, procedure (steps), expected results; actual result and status are filled in when executed.
Functions that are only designed (no code yet) are intentionally left out.
"""

CASES = [
    {
        "id": "TC01", "uc": "UC01", "name": "Đăng nhập",
        "goal": "Kiểm tra quản trị viên đăng nhập cổng quản trị bằng email và mật khẩu hợp lệ, phiên được lưu trong cookie HttpOnly và được chuyển về trang đã yêu cầu trước đó (returnTo).",
        "pre": ["Backend PAVEX đang chạy, kết nối PostgreSQL bình thường.",
                "Tồn tại tài khoản quản trị trạng thái Hoạt động, có quyền identity.users.read.",
                "Trình duyệt chưa có phiên đăng nhập."],
        "data": ["Email: admin@pavex.vn", "Mật khẩu: mật khẩu đúng của tài khoản"],
        "steps": ["Truy cập trực tiếp đường dẫn /identity/users khi chưa đăng nhập.",
                  "Quan sát trang được chuyển đến.",
                  "Nhập Email và Mật khẩu theo dữ liệu vào.",
                  "Nhấn nút “Vào bảng điều hành”."],
        "expected": ["Bước 2: hệ thống chuyển về /login?returnTo=/identity/users.",
                     "Bước 4: nút chuyển sang “Đang xác thực...”, sau đó chuyển đến trang Người dùng (/identity/users).",
                     "Cookie phiên được tạo với thuộc tính HttpOnly (không đọc được bằng JavaScript).",
                     "Thanh bên hiển thị tên và email của tài khoản; chỉ hiện các menu ứng với quyền của tài khoản."],
    },
    {
        "id": "TC02", "uc": "UC02", "name": "Đăng xuất",
        "goal": "Kiểm tra người dùng đăng xuất khỏi cổng quản trị: refresh token bị thu hồi, cookie phiên bị xóa và không thể truy cập lại các trang quản trị.",
        "pre": ["Đã đăng nhập cổng quản trị thành công (TC01).",
                "Đang ở trang Bảng điều hành (/dashboard)."],
        "data": ["Không có"],
        "steps": ["Nhấn nút “Đăng xuất” trên thanh bên.",
                  "Quan sát trang được chuyển đến.",
                  "Nhập lại đường dẫn /dashboard trên thanh địa chỉ."],
        "expected": ["Bước 1: cổng gửi yêu cầu đăng xuất, backend thu hồi refresh token; cookie phiên bị xóa.",
                     "Bước 2: chuyển về trang Đăng nhập (/login).",
                     "Bước 3: không vào được bảng điều hành, hệ thống chuyển về /login?returnTo=/dashboard."],
    },
    {
        "id": "TC03", "uc": "UC06", "name": "Tra cứu và lọc người dùng",
        "goal": "Kiểm tra quản trị viên xem danh sách tài khoản, tìm kiếm theo email/tên, lọc theo vai trò, trạng thái tài khoản, trạng thái hồ sơ và phân trang.",
        "pre": ["Đã đăng nhập bằng tài khoản có quyền identity.users.read.",
                "Hệ thống có hơn 20 tài khoản, trong đó có tài khoản khớp dữ liệu vào."],
        "data": ["Từ khóa: pavex", "Vai trò: một vai trò có trong danh sách",
                 "Trạng thái tài khoản: Hoạt động", "Trạng thái hồ sơ: Đã hoàn tất"],
        "steps": ["Chọn menu “Người dùng” trên thanh bên.",
                  "Nhấn “Sau” rồi “Trước” ở thanh phân trang.",
                  "Nhập từ khóa vào ô “Email hoặc tên...”.",
                  "Lần lượt chọn vai trò, trạng thái tài khoản và trạng thái hồ sơ theo dữ liệu vào.",
                  "Nhấn “Tải lại”."],
        "expected": ["Bước 1: hiển thị các chỉ số (Tổng tài khoản, Hoạt động / trang, Email xác minh, Hồ sơ hoàn tất) và bảng tài khoản, tối đa 20 dòng mỗi trang.",
                     "Bước 2: nhãn “Trang x/y” thay đổi đúng, danh sách đổi theo trang.",
                     "Bước 3–4: danh sách chỉ còn tài khoản có email hoặc tên chứa “pavex” và khớp cả ba bộ lọc; điều kiện lọc được ghi lên URL.",
                     "Bước 5: danh sách được tải lại và giữ nguyên điều kiện lọc."],
    },
    {
        "id": "TC04", "uc": "UC08", "name": "Xem vai trò và quyền",
        "goal": "Kiểm tra quản trị viên xem danh sách vai trò, chi tiết quyền của từng vai trò và tìm quyền theo tên hoặc mã.",
        "pre": ["Đã đăng nhập bằng tài khoản có quyền identity.roles.read.",
                "Hệ thống có các vai trò hệ thống đã được khởi tạo."],
        "data": ["Từ khóa tìm quyền: users"],
        "steps": ["Chọn menu “Vai trò & quyền” trên thanh bên.",
                  "Chọn một vai trò trong danh sách.",
                  "Nhập từ khóa vào ô “Tìm quyền theo tên hoặc mã...”.",
                  "Nhấn “Tải lại”."],
        "expected": ["Bước 1: hiển thị danh sách vai trò, mỗi vai trò có số quyền và nhãn “Vai trò hệ thống” nếu là vai trò hệ thống; vai trò đầu tiên được chọn sẵn.",
                     "Bước 2: hiển thị mô tả và danh sách quyền của vai trò đã chọn.",
                     "Bước 3: chỉ còn các quyền có tên hoặc mã chứa “users” (ví dụ identity.users.read).",
                     "Bước 4: danh sách vai trò được tải lại từ backend."],
    },
]
